options:

  auto-update: true

dungeons:

  world-name: dungeon

  basic:

    # If not specified, defaults to "schematics/{dungeon name}"
    config-location: dungeons/basic

  vivacious:

    cooldown: 1800
    timer: 600
    branching-factor: 1.25
    config-location: dungeons/vivacious

  tenebrous:

    cooldown: 1800
    timer: 600
    branching-factor: 1.25
    config-location: dungeons/tenebrous

  ancient:

    cooldown: 1800
    timer: 600
    branching-factor: 1.25
    config-location: dungeons/ancient