name: QuantumDungeons

author: SchnTgaiSpock

description: A Slimefun addon that adds infinite dungeons to Minecraft

main: io.github.schntgaispock.quantumdungeons.QuantumDungeons

website: https://github.com/SchnTgaiSpock/QuantumDungeons

version: ${project.version}

api-version: 1.14

depend:
- Slimefun

soft-depend:
- SlimeHUD

commands:
  slimehud:
    description: /quantumdungeons
    aliases: [qdungeons, qd]
    usage: Press [tab] for usage hints